from django.contrib import admin
from django.urls import path

from .views import (
    race_index,
    race_areas_list,
    area_delete,
    race_levels_list,
    level_delete,
    race_years_list,
    year_delete,
    race_colors_list,
    color_delete,
    race_sexs_list,
    sex_delete,
    race_list,
    race_delete,
    race_start,
    cancel_projection,
    change_projection,
    update_score,
    print_projection,
    finish_game,
    export_race_scores_to_csv,
    team_demo_levels_list,
    team_demo_level_delete,
    team_demo_race_list,
    team_demo_race_delete,
    team_demo_race_start,
    cancel_team_demo_projection,
    change_team_demo_projection,
    update_team_demo_score,
    print_team_demo_projection,
    finish_team_demo_game,
    score_add,
    score_edit,
    score_delete,
)

urlpatterns = [
    # 設定 url 路徑 與 要使用的 function， Django 的根目錄預設不用寫
    path("", race_index, name="raceindex"),
    path("area_edit/", race_areas_list, name="areaslist"),
    path("area_delete/<int:id>/", area_delete, name="areadelete"),
    path("level_edit/", race_levels_list, name="levelslist"),
    path("level_delete/<int:id>/", level_delete, name="leveldelete"),
    path("year_edit/", race_years_list, name="yearslist"),
    path("year_delete/<int:id>/", year_delete, name="yeardelete"),
    path("color_edit/", race_colors_list, name="colorslist"),
    path("color_delete/<int:id>/", color_delete, name="colordelete"),
    path("sex_edit/", race_sexs_list, name="sexslist"),
    path("sex_delete/<int:id>/", sex_delete, name="sexdelete"),
    path("sex_edit/", race_sexs_list, name="sexslist"),
    path("sex_delete/<int:id>/", sex_delete, name="sexdelete"),
    path("race_edit/", race_list, name="raceslist"),
    path("race_delete/<int:id>/", race_delete, name="racedelete"),
    path("race_start/<int:id>/", race_start, name="racestart"),
    path("cancel_projection/<int:id>/", cancel_projection, name="cancelprojection"),
    path("change_projection/", change_projection, name="changeprojection"),
    path("update_score/", update_score, name="updatescore"),
    path("print_projection/<int:id>/", print_projection, name="printprojection"),
    path("finish_game/<int:id>/", finish_game, name="finishgame"),
    path(
        "export_race_scores_to_csv/",
        export_race_scores_to_csv,
        name="exportracescorestocsv",
    ),
    path("team_demo_level_edit/", team_demo_levels_list, name="teamdemolevelslist"),
    path(
        "team_demo_level_delete/<int:id>/",
        team_demo_level_delete,
        name="teamdemoleveldelete",
    ),
    path("team_demo_race_edit/", team_demo_race_list, name="teamdemoraceslist"),
    path(
        "team_demo_race_delete/<int:id>/",
        team_demo_race_delete,
        name="teamdemoracedelete",
    ),
    path("team_demo_race_start/", team_demo_race_start, name="teamdemoracestart"),
    path(
        "cancel_team_demo_projection/",
        cancel_team_demo_projection,
        name="cancelteamdemoprojection",
    ),
    path(
        "change_team_demo_projection/",
        change_team_demo_projection,
        name="changeteamdemoprojection",
    ),
    path("update_team_demo_score/", update_team_demo_score, name="updateteamdemoscore"),
    path(
        "print_team_demo_projection/",
        print_team_demo_projection,
        name="printteamdemoprojection",
    ),
    path(
        "finish_team_demo_game/",
        finish_team_demo_game,
        name="finishteamdemogame",
    ),
    path("score_add/", score_add, name="scoreadd"),
    path("score_edit/<int:id>/", score_edit, name="scoreedit"),
    path("score_delete/<int:id>/", score_delete, name="scoredelete"),
]
