# Generated by Django 5.2.1 on 2025-06-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="race_scores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                ("referee_a_score", models.FloatField()),
                ("referee_b_score", models.FloatField()),
                ("referee_c_score", models.FloatField()),
                ("avg_score", models.FloatField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
