# Generated by Django 5.2.2 on 2025-06-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_scores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="race_areas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="race_colors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("color", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="race_levels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="race_sexs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sex", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="race_years",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name="race_scores",
            name="area",
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="race_scores",
            name="color",
            field=models.CharField(default=None, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="race_scores",
            name="level",
            field=models.CharField(default="1", max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="race_scores",
            name="sex",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="race_scores",
            name="year",
            field=models.CharField(default=1, max_length=5),
            preserve_default=False,
        ),
    ]
