# Generated by Django 5.2.2 on 2025-06-09 12:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_scores", "0002_race_areas_race_colors_race_levels_race_sexs_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race_scores",
            name="area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="race_scores.race_areas"
            ),
        ),
        migrations.AlterField(
            model_name="race_scores",
            name="color",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="race_scores.race_colors",
            ),
        ),
        migrations.AlterField(
            model_name="race_scores",
            name="level",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="race_scores.race_levels",
            ),
        ),
        migrations.AlterField(
            model_name="race_scores",
            name="sex",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="race_scores.race_sexs"
            ),
        ),
        migrations.AlterField(
            model_name="race_scores",
            name="year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="race_scores.race_years"
            ),
        ),
    ]
