# Generated by Django 5.2.2 on 2025-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_scores", "0003_alter_race_scores_area_alter_race_scores_color_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="race_scores",
            name="avg_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="race_scores",
            name="referee_a_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="race_scores",
            name="referee_b_score",
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name="race_scores",
            name="referee_c_score",
            field=models.FloatField(null=True),
        ),
    ]
