# Generated by Django 5.2.2 on 2025-06-10 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_scores", "0005_alter_race_scores_avg_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="race_scores",
            name="projection_tag",
            field=models.BooleanField(default=False),
        ),
    ]
