# Generated by Django 5.2.2 on 2025-06-19 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_scores", "0008_race_finish"),
    ]

    operations = [
        migrations.CreateModel(
            name="team_demo_levels",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("level", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="team_demo_scores",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_name", models.CharField(max_length=100)),
                ("referee_a_score", models.FloatField(blank=True, null=True)),
                ("referee_b_score", models.FloatField(blank=True, null=True)),
                ("referee_c_score", models.FloatField(blank=True, null=True)),
                ("referee_d_score", models.FloatField(blank=True, null=True)),
                ("referee_e_score", models.FloatField(blank=True, null=True)),
                ("sum_score", models.FloatField(blank=True, null=True)),
                ("projection_tag", models.BooleanField(default=False)),
                ("score_update", models.DateTimeField(blank=True, null=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_scores.team_demo_levels",
                    ),
                ),
            ],
        ),
    ]
