# Generated by Django 5.2.2 on 2025-06-19 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("race_scores", "0009_team_demo_levels_team_demo_scores"),
    ]

    operations = [
        migrations.CreateModel(
            name="team_demo_finish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "level",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="race_scores.team_demo_levels",
                    ),
                ),
            ],
        ),
    ]
